apiVersion: v1
kind: Service
metadata:
  name: dravaono-playground
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: dravaono-playground
  ports:
    - port: 8888
      targetPort: 8888
